services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - ./Backend/.env       # carga TODO el .env, incluyendo DATABASE_HOST=localhost
    environment:
      - DATABASE_HOST=db     # esta línea pisa el valor anterior
      - DATABASE_PORT=5432    # ← agregar esta línea
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: